version: '3.7'

services:
  server:
    container_name: pagarme-api
    entrypoint: [ "sh", "-c", "java -cp app:app/lib/* br.com.geradordedevs.pagarme.DesafioPagarMeApplication" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://pagarme-db:3306/db_pagarme?autoReconnect=true&useSSL=false
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db-pagarme
      - DATABASE_USER=db_pagarme
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=db_pagarme
      - DATABASE_PORT=3306
    depends_on:
      - db-pagarme
  db-pagarme:
    image: mysql:8.0
    container_name: pagarme-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_pagarme
      - MYSQL_USER=db_pagarme
      - MYSQL_PASSWORD=123456
    ports:
      - 3307:3306
    volumes:
      - ./data/db:/data/db
